import test from 'node:test';import assert from 'node:assert/strict';import{generate,validate,parseSide,estimate,GRID,LIMIT}from'../dist/geometry.mjs';
test('60×100 exact Euclidean squares',()=>assert.deepEqual(generate({mode:'basic'}).roots.map(s=>s.s/GRID/100),[60,40,20,20]));
test('equal sides: one base square, subdivided mosaic',()=>{assert.equal(generate({short:'100',long:'100',mode:'basic'}).leaves.length,1);assert.ok(generate({short:'100',long:'100',mode:'mosaic'}).leaves.length>1);});
for(const [a,b]of[['60','100'],['100','100'],['7','13'],['2.5','4'],['100','60'],['0.01','0.01'],['997.5','1000']])for(const mode of['basic','mosaic','focus'])for(const vertical of[false,true])test(`${a}×${b} ${mode} ${vertical?'portrait':'landscape'} exact geometry`,()=>{const m=generate({short:a,long:b,mode,vertical,detail:600});assert.equal(validate(m),true);const p=new Map(m.roots.map(s=>[s.id,s]));for(const e of m.events){assert(p.has(e.parent.id));p.delete(e.parent.id);for(const s of e.children){assert.equal(s.parent,e.parent.id);assert.equal(s.depth,e.parent.depth+1);assert.equal(s.s* Math.sqrt(e.children.length),e.parent.s);p.set(s.id,s);}}assert.deepEqual([...p.values()],m.leaves);});
test('all intermediate animation frames fully tile',()=>{const m=generate({detail:220,mode:'focus'});const p=new Map(m.roots.map(s=>[s.id,s]));validate(m,[...p.values()]);for(const e of m.events){p.delete(e.parent.id);e.children.forEach(s=>p.set(s.id,s));validate(m,[...p.values()]);}});
test('invalid inputs and extreme aspect ratio',()=>{for(const x of['','0','-1','NaN','Infinity','1e2','1.001','1000.01','abc','.'])assert.throws(()=>parseSide(x));assert.equal(parseSide('2.5'),250);assert.equal(parseSide('0.01'),1);assert.equal(estimate(100000,1),100000);assert.throws(()=>generate({short:'0.01',long:'1000'}),/100,000/);});
test('deterministic seeds and changed pattern',()=>{const opts={mode:'mosaic',detail:400,seed:'hello'};assert.deepEqual(generate(opts),generate(opts));assert.notDeepEqual(generate(opts).leaves,generate({...opts,seed:'world'}).leaves);});
test('validator rejects overlap even when areas match',()=>{const m=generate({short:'2',long:'4',mode:'basic'});assert.throws(()=>validate(m,[m.roots[0],{...m.roots[1],x:0}]),/重な/);assert.throws(()=>validate(m,[m.roots[0]]),/未充填/);assert.throws(()=>validate(m,[{...m.roots[0],x:-1},m.roots[1]]),/境界/);});
test('budget and depth limit under stress',()=>{for(const mode of['mosaic','focus']){const m=generate({detail:4000,mode,strength:100,focus:{x:0,y:0}});assert(m.leaves.length<=4000);assert(m.leaves.every(s=>s.depth<=8));validate(m);}assert.equal(generate({short:'0.01',long:'60',mode:'basic'}).leaves.length,LIMIT);});

