import test from 'node:test';import assert from 'node:assert/strict';
// Exercise the same event handlers as the Canvas UI with deterministic frames.
const elements=new Map();const attrs=new Map();const callbacks=new Map();let rid=0;
function node(id){if(!elements.has(id))elements.set(id,{id,value:({short:'60',long:'100',palette:'vivid',speed:'1',seed:'2048'})[id]||'',checked:id==='outlines',hidden:false,style:{},textContent:'',setAttribute(k,v){attrs.set(`${id}:${k}`,String(v));},addEventListener(k,f){this[k]=f;},getBoundingClientRect(){return{left:0,top:0,width:390,height:350};},setPointerCapture(){},getContext(){return new Proxy({},{get:()=>()=>{}});}});return elements.get(id);}
globalThis.document={getElementById:node,querySelectorAll:()=>[]};globalThis.window={addEventListener(){}};globalThis.devicePixelRatio=1;globalThis.matchMedia=()=>({matches:false,addEventListener(){}});globalThis.ResizeObserver=class{observe(){}};globalThis.requestAnimationFrame=f=>{callbacks.set(++rid,f);return rid;};globalThis.cancelAnimationFrame=id=>callbacks.delete(id);
await import('../dist/app.mjs');const canvas=node('canvas');
test('two-pointer pinch doubles zoom without selecting',()=>{canvas.onpointerdown({pointerId:1,clientX:100,clientY:100});canvas.onpointerdown({pointerId:2,clientX:200,clientY:100});canvas.onpointermove({pointerId:2,clientX:300,clientY:100});assert.equal(node('zoom').textContent,'200%');canvas.onpointerup({pointerId:2});canvas.onpointerup({pointerId:1});assert.equal(node('selection').hidden,true);node('fit').onclick();assert.equal(node('zoom').textContent,'100%');});
test('wheel zoom and drag retain finite view',()=>{canvas.wheel({preventDefault(){},deltaY:-200,clientX:180,clientY:150});assert.equal(node('zoom').textContent,'135%');canvas.onpointerdown({pointerId:1,clientX:100,clientY:100});canvas.onpointermove({pointerId:1,clientX:120,clientY:130});canvas.onpointerup({pointerId:1});assert.equal(node('selection').hidden,true);node('fit').onclick();});
test('regeneration cancels every old animation frame',()=>{for(let i=0;i<8;i++){node('play').onclick();assert.equal(callbacks.size,1);node('shuffle').onclick();assert.equal(callbacks.size,0);assert.equal(attrs.get('play:aria-label'),'分割アニメーションを再生');}assert.ok(Number(node('count').textContent.replaceAll(',',''))>1);});
test('pause and restart use one frame loop',()=>{node('play').onclick();assert.equal(callbacks.size,1);node('play').onclick();assert.equal(callbacks.size,0);node('restart').onclick();assert.equal(callbacks.size,1);node('play').onclick();assert.equal(callbacks.size,0);});
test('invalid generation keeps last complete result and displays error',()=>{const count=node('count').textContent;node('short').value='0';node('dimensions').onsubmit({preventDefault(){}});assert.equal(node('error').hidden,false);assert.equal(node('count').textContent,count);});
